# -*- coding: utf-8 -*-
"""aws_devops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CNYAzZo2VqKSyci6BJ7KZkOMx5WJSjM

AWS DEVOPS
"""

!pip install boto3

import boto3

aws_access_key = "Your access key"
aws_secret_key = "your secret key"
region = "us-east-1"

iam_client = boto3.client(
    'iam',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=region
)


# list IAM users

response = iam_client.list_users()
print(response)
print("Iam users in account :")
for user in response['Users']:
  username = user['UserName']
  user_id = user['UserId']
  created_date = user['CreateDate']
  print(f"Username: {username}, Created Date: {created_date}, UserID: {user_id}")

import boto3
aws_access_key = "Your access key"
aws_secret_key = "your secret key"
region = "us-east-1"

iam_client = boto3.client(
    'iam',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=region
)


# create a user

user_name = "learnbaystudent"

try:
  response =iam_client.create_user(UserName=user_name)
  print(f"IAM user '{user_name} created successfully")

except ClientError as error:
  if error.response['Error']['Code'] == 'EntityAlreadyExists':
    print(f"User '{user_name}' already exists.")
  else:
    print("error occurred:")
    print(error)

import boto3

# aws_access_key = "Your access key"
# aws_secret_key = "your secret key"
# region = "us-east-1"

s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=region
)


# list IAM users
response = s3.list_buckets()
print(response)

import boto3

# aws_access_key = "Your access key"
# aws_secret_key = "your secret key"
# region = "us-east-1"

s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=region
)


bucket_name = "ishikalearnbaydemobucket"

try :
  if region == "us-east-1":
    s3.create_bucket(Bucket=bucket_name)
  else:
   s3.create_bucket(Bucket=bucket_name, CreateBucketConfiguration = {'LocationConstraint': region})
  print(f"s3 bucket '{bucket_name}' created scuccessfully")

except ClientError as e:
  print("Failed to create a bucket")
  print(e)

import boto3

# aws_access_key = "Your access key"
# aws_secret_key = "your secret key"
# region = "us-east-1"

s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=region
)


bucket_name = "ishikalearnbaydemobucket"

try :
  if region == "us-east-1":
    s3.create_bucket(Bucket=bucket_name)
  else:
   s3.create_bucket(Bucket=bucket_name, CreateBucketConfiguration = {'LocationConstraint': region})
  print(f"s3 bucket '{bucket_name}' created scuccessfully")

except ClientError as e:
  print("Failed to create a bucket")
  print(e)

